export enum DialogType {
  UpdateAccount,
  UpdateProfile,
  UpdateAppearance,
  CreateCourse,
  UpdateCourse,
  CreateModule,
  UpdateModule,
  CreateAssignmentGroup,
  CreateAssignment,
  UpdateAssignmentGroup,
  UpdateAssignment,
  CreateOrganization,
  UpdateOrganization,
  CreateFile,
  UpdateFile,
}
