services:
  chalk.server:
    image: chalk.server
    build:
      context: chalk.Server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - chalk.database

  chalk.database:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    restart: "always"
    volumes:
      - chalk_psql:/var/lib/postgresql/data
  
  chalk.web:
    image: chalk.web
    build:
      context: chalk.Web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - chalk.server
      - chalk.database

volumes:
  chalk_psql: