services:
  chalk.s3:
    image: quay.io/minio/minio
    command: "minio server /data --console-address ':9001'"
    environment:
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - chalk_s3:/data
  
  chalk.database:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    restart: "always"
    volumes:
      - chalk_psql:/var/lib/postgresql/data
  
  chalk.server:
    image: chalk.server
    build:
      context: chalk.Server
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Key=${JWT_KEY}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - chalk.database
  
  chalk.web:
    image: chalk.web
    build:
      context: chalk.Web
      dockerfile: Dockerfile
    environment:
      - VITE_API_HOST=${VITE_API_HOST}
      - VITE_API_PORT=${VITE_API_PORT}
    ports:
      - "3000:3000"
    depends_on:
      - chalk.server
      - chalk.database
      - chalk.s3

volumes:
  chalk_s3:
  chalk_psql: